# Generated by Django 6.0 on 2025-12-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_maintenancejob_computer_alter_computersale_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chapa_secret_key",
                    models.CharField(
                        blank=True,
                        help_text="Chapa Secret Key for payment processing. Falls back to CHAPA_SECRET_KEY environment variable if not set.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "chapa_public_key",
                    models.CharField(
                        blank=True,
                        help_text="Chapa Public Key (optional, for frontend integration)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "frontend_url",
                    models.URLField(
                        blank=True,
                        help_text="Frontend URL where users are redirected after payment (e.g., https://yourapp.com or http://localhost:53841 for local dev)",
                        max_length=500,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
