# Generated by Django 6.0 on 2025-12-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="backend_url",
            field=models.URLField(
                blank=True,
                help_text="Backend URL for payment callbacks (e.g., https://store-management-56xj.onrender.com or http://127.0.0.1:8000 for local dev). Used for Chapa callback and return URLs.",
                max_length=500,
                null=True,
            ),
        ),
    ]
